/*
 * This file is generated by jOOQ.
 */
package db.tables.records;


import db.tables.BookmarksMod;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookmarksModRecord extends UpdatableRecordImpl<BookmarksModRecord> implements Record2<Integer, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.bookmarks_mod.saved_by</code>.
     */
    public BookmarksModRecord setSavedBy(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.bookmarks_mod.saved_by</code>.
     */
    public Integer getSavedBy() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.bookmarks_mod.last_mod</code>.
     */
    public BookmarksModRecord setLastMod(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.bookmarks_mod.last_mod</code>.
     */
    public LocalDateTime getLastMod() {
        return (LocalDateTime) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, LocalDateTime> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, LocalDateTime> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return BookmarksMod.BOOKMARKS_MOD.SAVED_BY;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return BookmarksMod.BOOKMARKS_MOD.LAST_MOD;
    }

    @Override
    public Integer component1() {
        return getSavedBy();
    }

    @Override
    public LocalDateTime component2() {
        return getLastMod();
    }

    @Override
    public Integer value1() {
        return getSavedBy();
    }

    @Override
    public LocalDateTime value2() {
        return getLastMod();
    }

    @Override
    public BookmarksModRecord value1(Integer value) {
        setSavedBy(value);
        return this;
    }

    @Override
    public BookmarksModRecord value2(LocalDateTime value) {
        setLastMod(value);
        return this;
    }

    @Override
    public BookmarksModRecord values(Integer value1, LocalDateTime value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookmarksModRecord
     */
    public BookmarksModRecord() {
        super(BookmarksMod.BOOKMARKS_MOD);
    }

    /**
     * Create a detached, initialised BookmarksModRecord
     */
    public BookmarksModRecord(Integer savedBy, LocalDateTime lastMod) {
        super(BookmarksMod.BOOKMARKS_MOD);

        setSavedBy(savedBy);
        setLastMod(lastMod);
    }
}
