/*
 * This file is generated by jOOQ.
 */
package db.tables.records;


import db.tables.FoundationRev;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FoundationRevRecord extends UpdatableRecordImpl<FoundationRevRecord> implements Record4<Integer, String, LocalDateTime, Integer> {

    private static final long serialVersionUID = -1928423936;

    /**
     * Setter for <code>public.foundation_rev.version</code>.
     */
    public FoundationRevRecord setVersion(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.foundation_rev.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.foundation_rev.description</code>.
     */
    public FoundationRevRecord setDescription(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.foundation_rev.description</code>.
     */
    public String getDescription() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.foundation_rev.migrated_on</code>.
     */
    public FoundationRevRecord setMigratedOn(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.foundation_rev.migrated_on</code>.
     */
    public LocalDateTime getMigratedOn() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.foundation_rev.execution_time_sec</code>.
     */
    public FoundationRevRecord setExecutionTimeSec(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.foundation_rev.execution_time_sec</code>.
     */
    public Integer getExecutionTimeSec() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, LocalDateTime, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, LocalDateTime, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return FoundationRev.FOUNDATION_REV.VERSION;
    }

    @Override
    public Field<String> field2() {
        return FoundationRev.FOUNDATION_REV.DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return FoundationRev.FOUNDATION_REV.MIGRATED_ON;
    }

    @Override
    public Field<Integer> field4() {
        return FoundationRev.FOUNDATION_REV.EXECUTION_TIME_SEC;
    }

    @Override
    public Integer component1() {
        return getVersion();
    }

    @Override
    public String component2() {
        return getDescription();
    }

    @Override
    public LocalDateTime component3() {
        return getMigratedOn();
    }

    @Override
    public Integer component4() {
        return getExecutionTimeSec();
    }

    @Override
    public Integer value1() {
        return getVersion();
    }

    @Override
    public String value2() {
        return getDescription();
    }

    @Override
    public LocalDateTime value3() {
        return getMigratedOn();
    }

    @Override
    public Integer value4() {
        return getExecutionTimeSec();
    }

    @Override
    public FoundationRevRecord value1(Integer value) {
        setVersion(value);
        return this;
    }

    @Override
    public FoundationRevRecord value2(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public FoundationRevRecord value3(LocalDateTime value) {
        setMigratedOn(value);
        return this;
    }

    @Override
    public FoundationRevRecord value4(Integer value) {
        setExecutionTimeSec(value);
        return this;
    }

    @Override
    public FoundationRevRecord values(Integer value1, String value2, LocalDateTime value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FoundationRevRecord
     */
    public FoundationRevRecord() {
        super(FoundationRev.FOUNDATION_REV);
    }

    /**
     * Create a detached, initialised FoundationRevRecord
     */
    public FoundationRevRecord(Integer version, String description, LocalDateTime migratedOn, Integer executionTimeSec) {
        super(FoundationRev.FOUNDATION_REV);

        set(0, version);
        set(1, description);
        set(2, migratedOn);
        set(3, executionTimeSec);
    }
}
