/*
 * This file is generated by jOOQ.
*/
package db.tables.records;


import db.enums.ShareMethod;
import db.tables.SharedFacts;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SharedFactsRecord extends TableRecordImpl<SharedFactsRecord> implements Record13<Integer, Timestamp, String, Integer, String, Integer, Integer, ShareMethod, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = 531973535;

    /**
     * Setter for <code>public.shared_facts.shared_by</code>.
     */
    public SharedFactsRecord setSharedBy(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.shared_by</code>.
     */
    public Integer getSharedBy() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.shared_facts.shared_on</code>.
     */
    public SharedFactsRecord setSharedOn(Timestamp value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.shared_on</code>.
     */
    public Timestamp getSharedOn() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>public.shared_facts.shared_ip</code>.
     */
    public SharedFactsRecord setSharedIp(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.shared_ip</code>.
     */
    public String getSharedIp() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.shared_facts.view_count</code>.
     */
    public SharedFactsRecord setViewCount(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.view_count</code>.
     */
    public Integer getViewCount() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.shared_facts.title</code>.
     */
    public SharedFactsRecord setTitle(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.title</code>.
     */
    public String getTitle() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.shared_facts.foundation_version</code>.
     */
    public SharedFactsRecord setFoundationVersion(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.foundation_version</code>.
     */
    public Integer getFoundationVersion() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.shared_facts.url_version</code>.
     */
    public SharedFactsRecord setUrlVersion(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.url_version</code>.
     */
    public Integer getUrlVersion() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.shared_facts.method</code>.
     */
    public SharedFactsRecord setMethod(ShareMethod value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.method</code>.
     */
    public ShareMethod getMethod() {
        return (ShareMethod) get(7);
    }

    /**
     * Setter for <code>public.shared_facts.fact_slug</code>.
     */
    public SharedFactsRecord setFactSlug(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.fact_slug</code>.
     */
    public String getFactSlug() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.shared_facts.highlight_start</code>.
     */
    public SharedFactsRecord setHighlightStart(BigDecimal value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.highlight_start</code>.
     */
    public BigDecimal getHighlightStart() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>public.shared_facts.highlight_end</code>.
     */
    public SharedFactsRecord setHighlightEnd(BigDecimal value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.highlight_end</code>.
     */
    public BigDecimal getHighlightEnd() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>public.shared_facts.view_start</code>.
     */
    public SharedFactsRecord setViewStart(BigDecimal value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.view_start</code>.
     */
    public BigDecimal getViewStart() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>public.shared_facts.view_end</code>.
     */
    public SharedFactsRecord setViewEnd(BigDecimal value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.view_end</code>.
     */
    public BigDecimal getViewEnd() {
        return (BigDecimal) get(12);
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Timestamp, String, Integer, String, Integer, Integer, ShareMethod, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Timestamp, String, Integer, String, Integer, Integer, ShareMethod, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SharedFacts.SHARED_FACTS.SHARED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return SharedFacts.SHARED_FACTS.SHARED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SharedFacts.SHARED_FACTS.SHARED_IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return SharedFacts.SHARED_FACTS.VIEW_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SharedFacts.SHARED_FACTS.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return SharedFacts.SHARED_FACTS.FOUNDATION_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return SharedFacts.SHARED_FACTS.URL_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ShareMethod> field8() {
        return SharedFacts.SHARED_FACTS.METHOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return SharedFacts.SHARED_FACTS.FACT_SLUG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field10() {
        return SharedFacts.SHARED_FACTS.HIGHLIGHT_START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field11() {
        return SharedFacts.SHARED_FACTS.HIGHLIGHT_END;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field12() {
        return SharedFacts.SHARED_FACTS.VIEW_START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field13() {
        return SharedFacts.SHARED_FACTS.VIEW_END;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getSharedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getSharedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSharedIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getViewCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getFoundationVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getUrlVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShareMethod component8() {
        return getMethod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getFactSlug();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component10() {
        return getHighlightStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component11() {
        return getHighlightEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component12() {
        return getViewStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component13() {
        return getViewEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getSharedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getSharedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSharedIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getViewCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getFoundationVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getUrlVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShareMethod value8() {
        return getMethod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getFactSlug();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value10() {
        return getHighlightStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value11() {
        return getHighlightEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value12() {
        return getViewStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value13() {
        return getViewEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedFactsRecord value1(Integer value) {
        setSharedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedFactsRecord value2(Timestamp value) {
        setSharedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedFactsRecord value3(String value) {
        setSharedIp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedFactsRecord value4(Integer value) {
        setViewCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedFactsRecord value5(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedFactsRecord value6(Integer value) {
        setFoundationVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedFactsRecord value7(Integer value) {
        setUrlVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedFactsRecord value8(ShareMethod value) {
        setMethod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedFactsRecord value9(String value) {
        setFactSlug(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedFactsRecord value10(BigDecimal value) {
        setHighlightStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedFactsRecord value11(BigDecimal value) {
        setHighlightEnd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedFactsRecord value12(BigDecimal value) {
        setViewStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedFactsRecord value13(BigDecimal value) {
        setViewEnd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedFactsRecord values(Integer value1, Timestamp value2, String value3, Integer value4, String value5, Integer value6, Integer value7, ShareMethod value8, String value9, BigDecimal value10, BigDecimal value11, BigDecimal value12, BigDecimal value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SharedFactsRecord
     */
    public SharedFactsRecord() {
        super(SharedFacts.SHARED_FACTS);
    }

    /**
     * Create a detached, initialised SharedFactsRecord
     */
    public SharedFactsRecord(Integer sharedBy, Timestamp sharedOn, String sharedIp, Integer viewCount, String title, Integer foundationVersion, Integer urlVersion, ShareMethod method, String factSlug, BigDecimal highlightStart, BigDecimal highlightEnd, BigDecimal viewStart, BigDecimal viewEnd) {
        super(SharedFacts.SHARED_FACTS);

        set(0, sharedBy);
        set(1, sharedOn);
        set(2, sharedIp);
        set(3, viewCount);
        set(4, title);
        set(5, foundationVersion);
        set(6, urlVersion);
        set(7, method);
        set(8, factSlug);
        set(9, highlightStart);
        set(10, highlightEnd);
        set(11, viewStart);
        set(12, viewEnd);
    }
}
