/*
 * This file is generated by jOOQ.
 */
package db.tables.records;


import db.tables.SharedUrlRev;

import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SharedUrlRevRecord extends UpdatableRecordImpl<SharedUrlRevRecord> implements Record3<Integer, String, Timestamp> {

    private static final long serialVersionUID = 1317844128;

    /**
     * Setter for <code>public.shared_url_rev.version</code>.
     */
    public SharedUrlRevRecord setVersion(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_url_rev.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.shared_url_rev.description</code>.
     */
    public SharedUrlRevRecord setDescription(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_url_rev.description</code>.
     */
    public String getDescription() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.shared_url_rev.created_on</code>.
     */
    public SharedUrlRevRecord setCreatedOn(Timestamp value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_url_rev.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Timestamp> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Timestamp> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return SharedUrlRev.SHARED_URL_REV.VERSION;
    }

    @Override
    public Field<String> field2() {
        return SharedUrlRev.SHARED_URL_REV.DESCRIPTION;
    }

    @Override
    public Field<Timestamp> field3() {
        return SharedUrlRev.SHARED_URL_REV.CREATED_ON;
    }

    @Override
    public Integer component1() {
        return getVersion();
    }

    @Override
    public String component2() {
        return getDescription();
    }

    @Override
    public Timestamp component3() {
        return getCreatedOn();
    }

    @Override
    public Integer value1() {
        return getVersion();
    }

    @Override
    public String value2() {
        return getDescription();
    }

    @Override
    public Timestamp value3() {
        return getCreatedOn();
    }

    @Override
    public SharedUrlRevRecord value1(Integer value) {
        setVersion(value);
        return this;
    }

    @Override
    public SharedUrlRevRecord value2(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public SharedUrlRevRecord value3(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public SharedUrlRevRecord values(Integer value1, String value2, Timestamp value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SharedUrlRevRecord
     */
    public SharedUrlRevRecord() {
        super(SharedUrlRev.SHARED_URL_REV);
    }

    /**
     * Create a detached, initialised SharedUrlRevRecord
     */
    public SharedUrlRevRecord(Integer version, String description, Timestamp createdOn) {
        super(SharedUrlRev.SHARED_URL_REV);

        set(0, version);
        set(1, description);
        set(2, createdOn);
    }
}
