/*
 * This file is generated by jOOQ.
 */
package db.tables.records;


import db.tables.SharedFacts;

import java.math.BigDecimal;
import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SharedFactsRecord extends TableRecordImpl<SharedFactsRecord> implements Record11<Integer, Timestamp, String, Integer, String, Integer, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = -1205679019;

    /**
     * Setter for <code>public.shared_facts.shared_by</code>.
     */
    public SharedFactsRecord setSharedBy(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.shared_by</code>.
     */
    public Integer getSharedBy() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.shared_facts.shared_on</code>.
     */
    public SharedFactsRecord setSharedOn(Timestamp value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.shared_on</code>.
     */
    public Timestamp getSharedOn() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>public.shared_facts.shared_ip</code>.
     */
    public SharedFactsRecord setSharedIp(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.shared_ip</code>.
     */
    public String getSharedIp() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.shared_facts.view_count</code>.
     */
    public SharedFactsRecord setViewCount(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.view_count</code>.
     */
    public Integer getViewCount() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.shared_facts.title</code>.
     */
    public SharedFactsRecord setTitle(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.title</code>.
     */
    public String getTitle() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.shared_facts.url_version</code>.
     */
    public SharedFactsRecord setUrlVersion(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.url_version</code>.
     */
    public Integer getUrlVersion() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.shared_facts.factid</code>.
     */
    public SharedFactsRecord setFactid(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.factid</code>.
     */
    public String getFactid() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.shared_facts.highlight_start</code>.
     */
    public SharedFactsRecord setHighlightStart(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.highlight_start</code>.
     */
    public BigDecimal getHighlightStart() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>public.shared_facts.highlight_end</code>.
     */
    public SharedFactsRecord setHighlightEnd(BigDecimal value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.highlight_end</code>.
     */
    public BigDecimal getHighlightEnd() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>public.shared_facts.view_start</code>.
     */
    public SharedFactsRecord setViewStart(BigDecimal value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.view_start</code>.
     */
    public BigDecimal getViewStart() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>public.shared_facts.view_end</code>.
     */
    public SharedFactsRecord setViewEnd(BigDecimal value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.view_end</code>.
     */
    public BigDecimal getViewEnd() {
        return (BigDecimal) get(10);
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Integer, Timestamp, String, Integer, String, Integer, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Integer, Timestamp, String, Integer, String, Integer, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return SharedFacts.SHARED_FACTS.SHARED_BY;
    }

    @Override
    public Field<Timestamp> field2() {
        return SharedFacts.SHARED_FACTS.SHARED_ON;
    }

    @Override
    public Field<String> field3() {
        return SharedFacts.SHARED_FACTS.SHARED_IP;
    }

    @Override
    public Field<Integer> field4() {
        return SharedFacts.SHARED_FACTS.VIEW_COUNT;
    }

    @Override
    public Field<String> field5() {
        return SharedFacts.SHARED_FACTS.TITLE;
    }

    @Override
    public Field<Integer> field6() {
        return SharedFacts.SHARED_FACTS.URL_VERSION;
    }

    @Override
    public Field<String> field7() {
        return SharedFacts.SHARED_FACTS.FACTID;
    }

    @Override
    public Field<BigDecimal> field8() {
        return SharedFacts.SHARED_FACTS.HIGHLIGHT_START;
    }

    @Override
    public Field<BigDecimal> field9() {
        return SharedFacts.SHARED_FACTS.HIGHLIGHT_END;
    }

    @Override
    public Field<BigDecimal> field10() {
        return SharedFacts.SHARED_FACTS.VIEW_START;
    }

    @Override
    public Field<BigDecimal> field11() {
        return SharedFacts.SHARED_FACTS.VIEW_END;
    }

    @Override
    public Integer component1() {
        return getSharedBy();
    }

    @Override
    public Timestamp component2() {
        return getSharedOn();
    }

    @Override
    public String component3() {
        return getSharedIp();
    }

    @Override
    public Integer component4() {
        return getViewCount();
    }

    @Override
    public String component5() {
        return getTitle();
    }

    @Override
    public Integer component6() {
        return getUrlVersion();
    }

    @Override
    public String component7() {
        return getFactid();
    }

    @Override
    public BigDecimal component8() {
        return getHighlightStart();
    }

    @Override
    public BigDecimal component9() {
        return getHighlightEnd();
    }

    @Override
    public BigDecimal component10() {
        return getViewStart();
    }

    @Override
    public BigDecimal component11() {
        return getViewEnd();
    }

    @Override
    public Integer value1() {
        return getSharedBy();
    }

    @Override
    public Timestamp value2() {
        return getSharedOn();
    }

    @Override
    public String value3() {
        return getSharedIp();
    }

    @Override
    public Integer value4() {
        return getViewCount();
    }

    @Override
    public String value5() {
        return getTitle();
    }

    @Override
    public Integer value6() {
        return getUrlVersion();
    }

    @Override
    public String value7() {
        return getFactid();
    }

    @Override
    public BigDecimal value8() {
        return getHighlightStart();
    }

    @Override
    public BigDecimal value9() {
        return getHighlightEnd();
    }

    @Override
    public BigDecimal value10() {
        return getViewStart();
    }

    @Override
    public BigDecimal value11() {
        return getViewEnd();
    }

    @Override
    public SharedFactsRecord value1(Integer value) {
        setSharedBy(value);
        return this;
    }

    @Override
    public SharedFactsRecord value2(Timestamp value) {
        setSharedOn(value);
        return this;
    }

    @Override
    public SharedFactsRecord value3(String value) {
        setSharedIp(value);
        return this;
    }

    @Override
    public SharedFactsRecord value4(Integer value) {
        setViewCount(value);
        return this;
    }

    @Override
    public SharedFactsRecord value5(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public SharedFactsRecord value6(Integer value) {
        setUrlVersion(value);
        return this;
    }

    @Override
    public SharedFactsRecord value7(String value) {
        setFactid(value);
        return this;
    }

    @Override
    public SharedFactsRecord value8(BigDecimal value) {
        setHighlightStart(value);
        return this;
    }

    @Override
    public SharedFactsRecord value9(BigDecimal value) {
        setHighlightEnd(value);
        return this;
    }

    @Override
    public SharedFactsRecord value10(BigDecimal value) {
        setViewStart(value);
        return this;
    }

    @Override
    public SharedFactsRecord value11(BigDecimal value) {
        setViewEnd(value);
        return this;
    }

    @Override
    public SharedFactsRecord values(Integer value1, Timestamp value2, String value3, Integer value4, String value5, Integer value6, String value7, BigDecimal value8, BigDecimal value9, BigDecimal value10, BigDecimal value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SharedFactsRecord
     */
    public SharedFactsRecord() {
        super(SharedFacts.SHARED_FACTS);
    }

    /**
     * Create a detached, initialised SharedFactsRecord
     */
    public SharedFactsRecord(Integer sharedBy, Timestamp sharedOn, String sharedIp, Integer viewCount, String title, Integer urlVersion, String factid, BigDecimal highlightStart, BigDecimal highlightEnd, BigDecimal viewStart, BigDecimal viewEnd) {
        super(SharedFacts.SHARED_FACTS);

        set(0, sharedBy);
        set(1, sharedOn);
        set(2, sharedIp);
        set(3, viewCount);
        set(4, title);
        set(5, urlVersion);
        set(6, factid);
        set(7, highlightStart);
        set(8, highlightEnd);
        set(9, viewStart);
        set(10, viewEnd);
    }
}
