/*
 * This file is generated by jOOQ.
*/
package db.tables.records;


import db.enums.ShareMethod;
import db.tables.SharedFacts;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SharedFactsRecord extends TableRecordImpl<SharedFactsRecord> implements Record10<Integer, String, Integer, Integer, ShareMethod, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = -1116782334;

    /**
     * Setter for <code>public.shared_facts.shared_by</code>.
     */
    public SharedFactsRecord setSharedBy(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.shared_by</code>.
     */
    public Integer getSharedBy() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.shared_facts.title</code>.
     */
    public SharedFactsRecord setTitle(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.shared_facts.foundation_version</code>.
     */
    public SharedFactsRecord setFoundationVersion(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.foundation_version</code>.
     */
    public Integer getFoundationVersion() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.shared_facts.url_version</code>.
     */
    public SharedFactsRecord setUrlVersion(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.url_version</code>.
     */
    public Integer getUrlVersion() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.shared_facts.method</code>.
     */
    public SharedFactsRecord setMethod(ShareMethod value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.method</code>.
     */
    public ShareMethod getMethod() {
        return (ShareMethod) get(4);
    }

    /**
     * Setter for <code>public.shared_facts.fact_slug</code>.
     */
    public SharedFactsRecord setFactSlug(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.fact_slug</code>.
     */
    public String getFactSlug() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.shared_facts.highlight_start</code>.
     */
    public SharedFactsRecord setHighlightStart(BigDecimal value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.highlight_start</code>.
     */
    public BigDecimal getHighlightStart() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>public.shared_facts.highlight_end</code>.
     */
    public SharedFactsRecord setHighlightEnd(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.highlight_end</code>.
     */
    public BigDecimal getHighlightEnd() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>public.shared_facts.view_start</code>.
     */
    public SharedFactsRecord setViewStart(BigDecimal value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.view_start</code>.
     */
    public BigDecimal getViewStart() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>public.shared_facts.view_end</code>.
     */
    public SharedFactsRecord setViewEnd(BigDecimal value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_facts.view_end</code>.
     */
    public BigDecimal getViewEnd() {
        return (BigDecimal) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, Integer, Integer, ShareMethod, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, Integer, Integer, ShareMethod, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SharedFacts.SHARED_FACTS.SHARED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SharedFacts.SHARED_FACTS.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return SharedFacts.SHARED_FACTS.FOUNDATION_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return SharedFacts.SHARED_FACTS.URL_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ShareMethod> field5() {
        return SharedFacts.SHARED_FACTS.METHOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SharedFacts.SHARED_FACTS.FACT_SLUG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field7() {
        return SharedFacts.SHARED_FACTS.HIGHLIGHT_START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field8() {
        return SharedFacts.SHARED_FACTS.HIGHLIGHT_END;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field9() {
        return SharedFacts.SHARED_FACTS.VIEW_START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field10() {
        return SharedFacts.SHARED_FACTS.VIEW_END;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getSharedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getFoundationVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getUrlVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShareMethod component5() {
        return getMethod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getFactSlug();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component7() {
        return getHighlightStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component8() {
        return getHighlightEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component9() {
        return getViewStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component10() {
        return getViewEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getSharedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getFoundationVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getUrlVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShareMethod value5() {
        return getMethod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getFactSlug();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value7() {
        return getHighlightStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value8() {
        return getHighlightEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value9() {
        return getViewStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value10() {
        return getViewEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedFactsRecord value1(Integer value) {
        setSharedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedFactsRecord value2(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedFactsRecord value3(Integer value) {
        setFoundationVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedFactsRecord value4(Integer value) {
        setUrlVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedFactsRecord value5(ShareMethod value) {
        setMethod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedFactsRecord value6(String value) {
        setFactSlug(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedFactsRecord value7(BigDecimal value) {
        setHighlightStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedFactsRecord value8(BigDecimal value) {
        setHighlightEnd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedFactsRecord value9(BigDecimal value) {
        setViewStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedFactsRecord value10(BigDecimal value) {
        setViewEnd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedFactsRecord values(Integer value1, String value2, Integer value3, Integer value4, ShareMethod value5, String value6, BigDecimal value7, BigDecimal value8, BigDecimal value9, BigDecimal value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SharedFactsRecord
     */
    public SharedFactsRecord() {
        super(SharedFacts.SHARED_FACTS);
    }

    /**
     * Create a detached, initialised SharedFactsRecord
     */
    public SharedFactsRecord(Integer sharedBy, String title, Integer foundationVersion, Integer urlVersion, ShareMethod method, String factSlug, BigDecimal highlightStart, BigDecimal highlightEnd, BigDecimal viewStart, BigDecimal viewEnd) {
        super(SharedFacts.SHARED_FACTS);

        set(0, sharedBy);
        set(1, title);
        set(2, foundationVersion);
        set(3, urlVersion);
        set(4, method);
        set(5, factSlug);
        set(6, highlightStart);
        set(7, highlightEnd);
        set(8, viewStart);
        set(9, viewEnd);
    }
}
