/*
 * This file is generated by jOOQ.
 */
package db.enums;


import db.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum Reaction implements EnumType {

    like("like"),

    bookmark("bookmark"),

    spam("spam"),

    illegal("illegal"),

    view("view"),

    harassment("harassment"),

    rulesviolation("rulesviolation");

    private final String literal;

    private Reaction(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "reaction";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
