/*
 * This file is generated by jOOQ.
*/
package db;


import db.tables.Account;
import db.tables.Confirmaccountlink;
import db.tables.FlywaySchemaHistory;
import db.tables.Follow;
import db.tables.FoundationRev;
import db.tables.Loginlink;
import db.tables.Moderator;
import db.tables.SharedFacts;
import db.tables.SharedUrlRev;
import db.tables.Takedraft;
import db.tables.Takepublished;
import db.tables.Takereaction;
import db.tables.Takerevision;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 885972787;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.account</code>.
     */
    public final Account ACCOUNT = db.tables.Account.ACCOUNT;

    /**
     * The table <code>public.confirmaccountlink</code>.
     */
    public final Confirmaccountlink CONFIRMACCOUNTLINK = db.tables.Confirmaccountlink.CONFIRMACCOUNTLINK;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = db.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.follow</code>.
     */
    public final Follow FOLLOW = db.tables.Follow.FOLLOW;

    /**
     * The table <code>public.foundation_rev</code>.
     */
    public final FoundationRev FOUNDATION_REV = db.tables.FoundationRev.FOUNDATION_REV;

    /**
     * The table <code>public.loginlink</code>.
     */
    public final Loginlink LOGINLINK = db.tables.Loginlink.LOGINLINK;

    /**
     * The table <code>public.moderator</code>.
     */
    public final Moderator MODERATOR = db.tables.Moderator.MODERATOR;

    /**
     * The table <code>public.shared_facts</code>.
     */
    public final SharedFacts SHARED_FACTS = db.tables.SharedFacts.SHARED_FACTS;

    /**
     * The table <code>public.shared_url_rev</code>.
     */
    public final SharedUrlRev SHARED_URL_REV = db.tables.SharedUrlRev.SHARED_URL_REV;

    /**
     * The table <code>public.takedraft</code>.
     */
    public final Takedraft TAKEDRAFT = db.tables.Takedraft.TAKEDRAFT;

    /**
     * The table <code>public.takepublished</code>.
     */
    public final Takepublished TAKEPUBLISHED = db.tables.Takepublished.TAKEPUBLISHED;

    /**
     * The table <code>public.takereaction</code>.
     */
    public final Takereaction TAKEREACTION = db.tables.Takereaction.TAKEREACTION;

    /**
     * The table <code>public.takerevision</code>.
     */
    public final Takerevision TAKEREVISION = db.tables.Takerevision.TAKEREVISION;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ACCOUNT_ID_SEQ,
            Sequences.TAKEDRAFT_ID_SEQ,
            Sequences.TAKEPUBLISHED_ID_SEQ,
            Sequences.TAKEREVISION_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Account.ACCOUNT,
            Confirmaccountlink.CONFIRMACCOUNTLINK,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Follow.FOLLOW,
            FoundationRev.FOUNDATION_REV,
            Loginlink.LOGINLINK,
            Moderator.MODERATOR,
            SharedFacts.SHARED_FACTS,
            SharedUrlRev.SHARED_URL_REV,
            Takedraft.TAKEDRAFT,
            Takepublished.TAKEPUBLISHED,
            Takereaction.TAKEREACTION,
            Takerevision.TAKEREVISION);
    }
}
