/*
 * This file is generated by jOOQ.
*/
package db;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.account_id_seq</code>
     */
    public static final Sequence<Integer> ACCOUNT_ID_SEQ = new SequenceImpl<Integer>("account_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.takedraft_id_seq</code>
     */
    public static final Sequence<Integer> TAKEDRAFT_ID_SEQ = new SequenceImpl<Integer>("takedraft_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.takepublished_id_seq</code>
     */
    public static final Sequence<Integer> TAKEPUBLISHED_ID_SEQ = new SequenceImpl<Integer>("takepublished_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.takerevision_id_seq</code>
     */
    public static final Sequence<Integer> TAKEREVISION_ID_SEQ = new SequenceImpl<Integer>("takerevision_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
