/*
 * This file is generated by jOOQ.
 */
package db;


import db.tables.Account;
import db.tables.Confirmaccountlink;
import db.tables.FlywaySchemaHistory;
import db.tables.Follow;
import db.tables.FoundationRev;
import db.tables.Loginlink;
import db.tables.Moderator;
import db.tables.Takedraft;
import db.tables.Takepublished;
import db.tables.Takereaction;
import db.tables.Takerevision;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>public.confirmaccountlink</code>.
     */
    public static final Confirmaccountlink CONFIRMACCOUNTLINK = Confirmaccountlink.CONFIRMACCOUNTLINK;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.follow</code>.
     */
    public static final Follow FOLLOW = Follow.FOLLOW;

    /**
     * The table <code>public.foundation_rev</code>.
     */
    public static final FoundationRev FOUNDATION_REV = FoundationRev.FOUNDATION_REV;

    /**
     * The table <code>public.loginlink</code>.
     */
    public static final Loginlink LOGINLINK = Loginlink.LOGINLINK;

    /**
     * The table <code>public.moderator</code>.
     */
    public static final Moderator MODERATOR = Moderator.MODERATOR;

    /**
     * The table <code>public.takedraft</code>.
     */
    public static final Takedraft TAKEDRAFT = Takedraft.TAKEDRAFT;

    /**
     * The table <code>public.takepublished</code>.
     */
    public static final Takepublished TAKEPUBLISHED = Takepublished.TAKEPUBLISHED;

    /**
     * The table <code>public.takereaction</code>.
     */
    public static final Takereaction TAKEREACTION = Takereaction.TAKEREACTION;

    /**
     * The table <code>public.takerevision</code>.
     */
    public static final Takerevision TAKEREVISION = Takerevision.TAKEREVISION;
}
