/*
 * This file is generated by jOOQ.
*/
package db;


import db.tables.Account;
import db.tables.Confirmaccountlink;
import db.tables.FlywaySchemaHistory;
import db.tables.Follow;
import db.tables.FoundationRev;
import db.tables.Loginlink;
import db.tables.Moderator;
import db.tables.Takedraft;
import db.tables.Takepublished;
import db.tables.Takereaction;
import db.tables.Takerevision;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final Account ACCOUNT = db.tables.Account.ACCOUNT;

    /**
     * The table <code>public.confirmaccountlink</code>.
     */
    public static final Confirmaccountlink CONFIRMACCOUNTLINK = db.tables.Confirmaccountlink.CONFIRMACCOUNTLINK;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = db.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.follow</code>.
     */
    public static final Follow FOLLOW = db.tables.Follow.FOLLOW;

    /**
     * The table <code>public.foundation_rev</code>.
     */
    public static final FoundationRev FOUNDATION_REV = db.tables.FoundationRev.FOUNDATION_REV;

    /**
     * The table <code>public.loginlink</code>.
     */
    public static final Loginlink LOGINLINK = db.tables.Loginlink.LOGINLINK;

    /**
     * The table <code>public.moderator</code>.
     */
    public static final Moderator MODERATOR = db.tables.Moderator.MODERATOR;

    /**
     * The table <code>public.takedraft</code>.
     */
    public static final Takedraft TAKEDRAFT = db.tables.Takedraft.TAKEDRAFT;

    /**
     * The table <code>public.takepublished</code>.
     */
    public static final Takepublished TAKEPUBLISHED = db.tables.Takepublished.TAKEPUBLISHED;

    /**
     * The table <code>public.takereaction</code>.
     */
    public static final Takereaction TAKEREACTION = db.tables.Takereaction.TAKEREACTION;

    /**
     * The table <code>public.takerevision</code>.
     */
    public static final Takerevision TAKEREVISION = db.tables.Takerevision.TAKEREVISION;
}
