/*
 * This file is generated by jOOQ.
 */
package db.tables;


import db.Keys;
import db.Public;
import db.tables.records.BookmarkRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bookmark extends TableImpl<BookmarkRecord> {

    private static final long serialVersionUID = 829794012;

    /**
     * The reference instance of <code>public.bookmark</code>
     */
    public static final Bookmark BOOKMARK = new Bookmark();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BookmarkRecord> getRecordType() {
        return BookmarkRecord.class;
    }

    /**
     * The column <code>public.bookmark.saved_by</code>.
     */
    public final TableField<BookmarkRecord, Integer> SAVED_BY = createField(DSL.name("saved_by"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.bookmark.saved_on</code>.
     */
    public final TableField<BookmarkRecord, Timestamp> SAVED_ON = createField(DSL.name("saved_on"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>public.bookmark.fact_hash</code>.
     */
    public final TableField<BookmarkRecord, String> FACT_HASH = createField(DSL.name("fact_hash"), org.jooq.impl.SQLDataType.CHAR(44).nullable(false), this, "");

    /**
     * The column <code>public.bookmark.cut_start</code>.
     */
    public final TableField<BookmarkRecord, Integer> CUT_START = createField(DSL.name("cut_start"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.bookmark.cut_end</code>.
     */
    public final TableField<BookmarkRecord, Integer> CUT_END = createField(DSL.name("cut_end"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>public.bookmark</code> table reference
     */
    public Bookmark() {
        this(DSL.name("bookmark"), null);
    }

    /**
     * Create an aliased <code>public.bookmark</code> table reference
     */
    public Bookmark(String alias) {
        this(DSL.name(alias), BOOKMARK);
    }

    /**
     * Create an aliased <code>public.bookmark</code> table reference
     */
    public Bookmark(Name alias) {
        this(alias, BOOKMARK);
    }

    private Bookmark(Name alias, Table<BookmarkRecord> aliased) {
        this(alias, aliased, null);
    }

    private Bookmark(Name alias, Table<BookmarkRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Bookmark(Table<O> child, ForeignKey<O, BookmarkRecord> key) {
        super(child, key, BOOKMARK);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<BookmarkRecord> getPrimaryKey() {
        return Keys.BOOKMARK_PKEY;
    }

    @Override
    public List<UniqueKey<BookmarkRecord>> getKeys() {
        return Arrays.<UniqueKey<BookmarkRecord>>asList(Keys.BOOKMARK_PKEY);
    }

    @Override
    public List<ForeignKey<BookmarkRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<BookmarkRecord, ?>>asList(Keys.BOOKMARK__BOOKMARK_SAVED_BY_FKEY);
    }

    public Account account() {
        return new Account(this, Keys.BOOKMARK__BOOKMARK_SAVED_BY_FKEY);
    }

    @Override
    public Bookmark as(String alias) {
        return new Bookmark(DSL.name(alias), this);
    }

    @Override
    public Bookmark as(Name alias) {
        return new Bookmark(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Bookmark rename(String name) {
        return new Bookmark(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Bookmark rename(Name name) {
        return new Bookmark(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Timestamp, String, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
