/*
 * This file is generated by jOOQ.
*/
package db.tables;


import db.Indexes;
import db.Keys;
import db.Public;
import db.tables.records.TakedraftRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Takedraft extends TableImpl<TakedraftRecord> {

    private static final long serialVersionUID = -973267276;

    /**
     * The reference instance of <code>public.takedraft</code>
     */
    public static final Takedraft TAKEDRAFT = new Takedraft();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TakedraftRecord> getRecordType() {
        return TakedraftRecord.class;
    }

    /**
     * The column <code>public.takedraft.id</code>.
     */
    public final TableField<TakedraftRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('takedraft_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.takedraft.user_id</code>.
     */
    public final TableField<TakedraftRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.takedraft.last_revision</code>.
     */
    public final TableField<TakedraftRecord, Integer> LAST_REVISION = createField("last_revision", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>public.takedraft</code> table reference
     */
    public Takedraft() {
        this(DSL.name("takedraft"), null);
    }

    /**
     * Create an aliased <code>public.takedraft</code> table reference
     */
    public Takedraft(String alias) {
        this(DSL.name(alias), TAKEDRAFT);
    }

    /**
     * Create an aliased <code>public.takedraft</code> table reference
     */
    public Takedraft(Name alias) {
        this(alias, TAKEDRAFT);
    }

    private Takedraft(Name alias, Table<TakedraftRecord> aliased) {
        this(alias, aliased, null);
    }

    private Takedraft(Name alias, Table<TakedraftRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TAKEDRAFT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TakedraftRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TAKEDRAFT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TakedraftRecord> getPrimaryKey() {
        return Keys.TAKEDRAFT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TakedraftRecord>> getKeys() {
        return Arrays.<UniqueKey<TakedraftRecord>>asList(Keys.TAKEDRAFT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TakedraftRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TakedraftRecord, ?>>asList(Keys.TAKEDRAFT__TAKEDRAFT_USER_ID_FKEY, Keys.TAKEDRAFT__TAKEDRAFT_LAST_REVISION_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Takedraft as(String alias) {
        return new Takedraft(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Takedraft as(Name alias) {
        return new Takedraft(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Takedraft rename(String name) {
        return new Takedraft(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Takedraft rename(Name name) {
        return new Takedraft(name, null);
    }
}
