/*
 * This file is generated by jOOQ.
 */
package db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Account implements Serializable {

    private static final long serialVersionUID = -980992299;

    private Integer       id;
    private String        username;
    private String        email;
    private String        name;
    private LocalDateTime createdAt;
    private String        createdIp;
    private LocalDateTime updatedAt;
    private String        updatedIp;
    private LocalDateTime lastSeenAt;
    private String        lastSeenIp;
    private LocalDateTime lastEmailedAt;

    public Account() {}

    public Account(Account value) {
        this.id = value.id;
        this.username = value.username;
        this.email = value.email;
        this.name = value.name;
        this.createdAt = value.createdAt;
        this.createdIp = value.createdIp;
        this.updatedAt = value.updatedAt;
        this.updatedIp = value.updatedIp;
        this.lastSeenAt = value.lastSeenAt;
        this.lastSeenIp = value.lastSeenIp;
        this.lastEmailedAt = value.lastEmailedAt;
    }

    public Account(
        Integer       id,
        String        username,
        String        email,
        String        name,
        LocalDateTime createdAt,
        String        createdIp,
        LocalDateTime updatedAt,
        String        updatedIp,
        LocalDateTime lastSeenAt,
        String        lastSeenIp,
        LocalDateTime lastEmailedAt
    ) {
        this.id = id;
        this.username = username;
        this.email = email;
        this.name = name;
        this.createdAt = createdAt;
        this.createdIp = createdIp;
        this.updatedAt = updatedAt;
        this.updatedIp = updatedIp;
        this.lastSeenAt = lastSeenAt;
        this.lastSeenIp = lastSeenIp;
        this.lastEmailedAt = lastEmailedAt;
    }

    public Integer getId() {
        return this.id;
    }

    public Account setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getUsername() {
        return this.username;
    }

    public Account setUsername(String username) {
        this.username = username;
        return this;
    }

    public String getEmail() {
        return this.email;
    }

    public Account setEmail(String email) {
        this.email = email;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public Account setName(String name) {
        this.name = name;
        return this;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public Account setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    public String getCreatedIp() {
        return this.createdIp;
    }

    public Account setCreatedIp(String createdIp) {
        this.createdIp = createdIp;
        return this;
    }

    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    public Account setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    public String getUpdatedIp() {
        return this.updatedIp;
    }

    public Account setUpdatedIp(String updatedIp) {
        this.updatedIp = updatedIp;
        return this;
    }

    public LocalDateTime getLastSeenAt() {
        return this.lastSeenAt;
    }

    public Account setLastSeenAt(LocalDateTime lastSeenAt) {
        this.lastSeenAt = lastSeenAt;
        return this;
    }

    public String getLastSeenIp() {
        return this.lastSeenIp;
    }

    public Account setLastSeenIp(String lastSeenIp) {
        this.lastSeenIp = lastSeenIp;
        return this;
    }

    public LocalDateTime getLastEmailedAt() {
        return this.lastEmailedAt;
    }

    public Account setLastEmailedAt(LocalDateTime lastEmailedAt) {
        this.lastEmailedAt = lastEmailedAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Account (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(email);
        sb.append(", ").append(name);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(createdIp);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(updatedIp);
        sb.append(", ").append(lastSeenAt);
        sb.append(", ").append(lastSeenIp);
        sb.append(", ").append(lastEmailedAt);

        sb.append(")");
        return sb.toString();
    }
}
