/*
 * This file is generated by jOOQ.
 */
package db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bookmark implements Serializable {

    private static final long serialVersionUID = -460513084;

    private Integer   savedBy;
    private Timestamp savedOn;
    private String    factHash;
    private Integer   cutStart;
    private Integer   cutEnd;

    public Bookmark() {}

    public Bookmark(Bookmark value) {
        this.savedBy = value.savedBy;
        this.savedOn = value.savedOn;
        this.factHash = value.factHash;
        this.cutStart = value.cutStart;
        this.cutEnd = value.cutEnd;
    }

    public Bookmark(
        Integer   savedBy,
        Timestamp savedOn,
        String    factHash,
        Integer   cutStart,
        Integer   cutEnd
    ) {
        this.savedBy = savedBy;
        this.savedOn = savedOn;
        this.factHash = factHash;
        this.cutStart = cutStart;
        this.cutEnd = cutEnd;
    }

    public Integer getSavedBy() {
        return this.savedBy;
    }

    public Bookmark setSavedBy(Integer savedBy) {
        this.savedBy = savedBy;
        return this;
    }

    public Timestamp getSavedOn() {
        return this.savedOn;
    }

    public Bookmark setSavedOn(Timestamp savedOn) {
        this.savedOn = savedOn;
        return this;
    }

    public String getFactHash() {
        return this.factHash;
    }

    public Bookmark setFactHash(String factHash) {
        this.factHash = factHash;
        return this;
    }

    public Integer getCutStart() {
        return this.cutStart;
    }

    public Bookmark setCutStart(Integer cutStart) {
        this.cutStart = cutStart;
        return this;
    }

    public Integer getCutEnd() {
        return this.cutEnd;
    }

    public Bookmark setCutEnd(Integer cutEnd) {
        this.cutEnd = cutEnd;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Bookmark (");

        sb.append(savedBy);
        sb.append(", ").append(savedOn);
        sb.append(", ").append(factHash);
        sb.append(", ").append(cutStart);
        sb.append(", ").append(cutEnd);

        sb.append(")");
        return sb.toString();
    }
}
