/*
 * This file is generated by jOOQ.
 */
package db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookmarksMod implements Serializable {

    private static final long serialVersionUID = -1854501233;

    private Integer       savedBy;
    private LocalDateTime lastMod;

    public BookmarksMod() {}

    public BookmarksMod(BookmarksMod value) {
        this.savedBy = value.savedBy;
        this.lastMod = value.lastMod;
    }

    public BookmarksMod(
        Integer       savedBy,
        LocalDateTime lastMod
    ) {
        this.savedBy = savedBy;
        this.lastMod = lastMod;
    }

    public Integer getSavedBy() {
        return this.savedBy;
    }

    public BookmarksMod setSavedBy(Integer savedBy) {
        this.savedBy = savedBy;
        return this;
    }

    public LocalDateTime getLastMod() {
        return this.lastMod;
    }

    public BookmarksMod setLastMod(LocalDateTime lastMod) {
        this.lastMod = lastMod;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BookmarksMod (");

        sb.append(savedBy);
        sb.append(", ").append(lastMod);

        sb.append(")");
        return sb.toString();
    }
}
