/*
 * This file is generated by jOOQ.
 */
package db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bookmark implements Serializable {

    private static final long serialVersionUID = 1466561317;

    private Integer       savedBy;
    private LocalDateTime savedOn;
    private String        fact;
    private Integer       cutStart;
    private Integer       cutEnd;

    public Bookmark() {}

    public Bookmark(Bookmark value) {
        this.savedBy = value.savedBy;
        this.savedOn = value.savedOn;
        this.fact = value.fact;
        this.cutStart = value.cutStart;
        this.cutEnd = value.cutEnd;
    }

    public Bookmark(
        Integer       savedBy,
        LocalDateTime savedOn,
        String        fact,
        Integer       cutStart,
        Integer       cutEnd
    ) {
        this.savedBy = savedBy;
        this.savedOn = savedOn;
        this.fact = fact;
        this.cutStart = cutStart;
        this.cutEnd = cutEnd;
    }

    public Integer getSavedBy() {
        return this.savedBy;
    }

    public Bookmark setSavedBy(Integer savedBy) {
        this.savedBy = savedBy;
        return this;
    }

    public LocalDateTime getSavedOn() {
        return this.savedOn;
    }

    public Bookmark setSavedOn(LocalDateTime savedOn) {
        this.savedOn = savedOn;
        return this;
    }

    public String getFact() {
        return this.fact;
    }

    public Bookmark setFact(String fact) {
        this.fact = fact;
        return this;
    }

    public Integer getCutStart() {
        return this.cutStart;
    }

    public Bookmark setCutStart(Integer cutStart) {
        this.cutStart = cutStart;
        return this;
    }

    public Integer getCutEnd() {
        return this.cutEnd;
    }

    public Bookmark setCutEnd(Integer cutEnd) {
        this.cutEnd = cutEnd;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Bookmark (");

        sb.append(savedBy);
        sb.append(", ").append(savedOn);
        sb.append(", ").append(fact);
        sb.append(", ").append(cutStart);
        sb.append(", ").append(cutEnd);

        sb.append(")");
        return sb.toString();
    }
}
