/*
 * This file is generated by jOOQ.
 */
package db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Confirmaccountlink implements Serializable {

    private static final long serialVersionUID = 1710837149;

    private String        code;
    private LocalDateTime createdAt;
    private LocalDateTime expiresAt;
    private String        requestorIp;
    private String        username;
    private String        email;

    public Confirmaccountlink() {}

    public Confirmaccountlink(Confirmaccountlink value) {
        this.code = value.code;
        this.createdAt = value.createdAt;
        this.expiresAt = value.expiresAt;
        this.requestorIp = value.requestorIp;
        this.username = value.username;
        this.email = value.email;
    }

    public Confirmaccountlink(
        String        code,
        LocalDateTime createdAt,
        LocalDateTime expiresAt,
        String        requestorIp,
        String        username,
        String        email
    ) {
        this.code = code;
        this.createdAt = createdAt;
        this.expiresAt = expiresAt;
        this.requestorIp = requestorIp;
        this.username = username;
        this.email = email;
    }

    public String getCode() {
        return this.code;
    }

    public Confirmaccountlink setCode(String code) {
        this.code = code;
        return this;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public Confirmaccountlink setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    public LocalDateTime getExpiresAt() {
        return this.expiresAt;
    }

    public Confirmaccountlink setExpiresAt(LocalDateTime expiresAt) {
        this.expiresAt = expiresAt;
        return this;
    }

    public String getRequestorIp() {
        return this.requestorIp;
    }

    public Confirmaccountlink setRequestorIp(String requestorIp) {
        this.requestorIp = requestorIp;
        return this;
    }

    public String getUsername() {
        return this.username;
    }

    public Confirmaccountlink setUsername(String username) {
        this.username = username;
        return this;
    }

    public String getEmail() {
        return this.email;
    }

    public Confirmaccountlink setEmail(String email) {
        this.email = email;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Confirmaccountlink (");

        sb.append(code);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(expiresAt);
        sb.append(", ").append(requestorIp);
        sb.append(", ").append(username);
        sb.append(", ").append(email);

        sb.append(")");
        return sb.toString();
    }
}
