/*
 * This file is generated by jOOQ.
 */
package db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Follow implements Serializable {

    private static final long serialVersionUID = 1781904899;

    private Integer       author;
    private Integer       follower;
    private LocalDateTime followedAt;

    public Follow() {}

    public Follow(Follow value) {
        this.author = value.author;
        this.follower = value.follower;
        this.followedAt = value.followedAt;
    }

    public Follow(
        Integer       author,
        Integer       follower,
        LocalDateTime followedAt
    ) {
        this.author = author;
        this.follower = follower;
        this.followedAt = followedAt;
    }

    public Integer getAuthor() {
        return this.author;
    }

    public Follow setAuthor(Integer author) {
        this.author = author;
        return this;
    }

    public Integer getFollower() {
        return this.follower;
    }

    public Follow setFollower(Integer follower) {
        this.follower = follower;
        return this;
    }

    public LocalDateTime getFollowedAt() {
        return this.followedAt;
    }

    public Follow setFollowedAt(LocalDateTime followedAt) {
        this.followedAt = followedAt;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Follow (");

        sb.append(author);
        sb.append(", ").append(follower);
        sb.append(", ").append(followedAt);

        sb.append(")");
        return sb.toString();
    }
}
