/*
 * This file is generated by jOOQ.
*/
package db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Moderator implements Serializable {

    private static final long serialVersionUID = 775532744;

    private Integer id;

    public Moderator() {}

    public Moderator(Moderator value) {
        this.id = value.id;
    }

    public Moderator(
        Integer id
    ) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

    public Moderator setId(Integer id) {
        this.id = id;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Moderator (");

        sb.append(id);

        sb.append(")");
        return sb.toString();
    }
}
