/*
 * This file is generated by jOOQ.
 */
package db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Moderator implements Serializable {

    private static final long serialVersionUID = 1159163079;

    private Integer id;

    public Moderator() {}

    public Moderator(Moderator value) {
        this.id = value.id;
    }

    public Moderator(
        Integer id
    ) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

    public Moderator setId(Integer id) {
        this.id = id;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Moderator (");

        sb.append(id);

        sb.append(")");
        return sb.toString();
    }
}
