/*
 * This file is generated by jOOQ.
*/
package db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SharedUrlRev implements Serializable {

    private static final long serialVersionUID = -1969833888;

    private Integer   version;
    private String    description;
    private Timestamp createdOn;

    public SharedUrlRev() {}

    public SharedUrlRev(SharedUrlRev value) {
        this.version = value.version;
        this.description = value.description;
        this.createdOn = value.createdOn;
    }

    public SharedUrlRev(
        Integer   version,
        String    description,
        Timestamp createdOn
    ) {
        this.version = version;
        this.description = description;
        this.createdOn = createdOn;
    }

    public Integer getVersion() {
        return this.version;
    }

    public SharedUrlRev setVersion(Integer version) {
        this.version = version;
        return this;
    }

    public String getDescription() {
        return this.description;
    }

    public SharedUrlRev setDescription(String description) {
        this.description = description;
        return this;
    }

    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    public SharedUrlRev setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SharedUrlRev (");

        sb.append(version);
        sb.append(", ").append(description);
        sb.append(", ").append(createdOn);

        sb.append(")");
        return sb.toString();
    }
}
