/*
 * This file is generated by jOOQ.
*/
package db.tables.pojos;


import db.enums.ShareMethod;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SharedFacts implements Serializable {

    private static final long serialVersionUID = 1818712794;

    private Integer     sharedBy;
    private String      title;
    private Integer     foundationVersion;
    private Integer     urlVersion;
    private ShareMethod method;
    private String      factSlug;
    private BigDecimal  highlightStart;
    private BigDecimal  highlightEnd;
    private BigDecimal  viewStart;
    private BigDecimal  viewEnd;

    public SharedFacts() {}

    public SharedFacts(SharedFacts value) {
        this.sharedBy = value.sharedBy;
        this.title = value.title;
        this.foundationVersion = value.foundationVersion;
        this.urlVersion = value.urlVersion;
        this.method = value.method;
        this.factSlug = value.factSlug;
        this.highlightStart = value.highlightStart;
        this.highlightEnd = value.highlightEnd;
        this.viewStart = value.viewStart;
        this.viewEnd = value.viewEnd;
    }

    public SharedFacts(
        Integer     sharedBy,
        String      title,
        Integer     foundationVersion,
        Integer     urlVersion,
        ShareMethod method,
        String      factSlug,
        BigDecimal  highlightStart,
        BigDecimal  highlightEnd,
        BigDecimal  viewStart,
        BigDecimal  viewEnd
    ) {
        this.sharedBy = sharedBy;
        this.title = title;
        this.foundationVersion = foundationVersion;
        this.urlVersion = urlVersion;
        this.method = method;
        this.factSlug = factSlug;
        this.highlightStart = highlightStart;
        this.highlightEnd = highlightEnd;
        this.viewStart = viewStart;
        this.viewEnd = viewEnd;
    }

    public Integer getSharedBy() {
        return this.sharedBy;
    }

    public SharedFacts setSharedBy(Integer sharedBy) {
        this.sharedBy = sharedBy;
        return this;
    }

    public String getTitle() {
        return this.title;
    }

    public SharedFacts setTitle(String title) {
        this.title = title;
        return this;
    }

    public Integer getFoundationVersion() {
        return this.foundationVersion;
    }

    public SharedFacts setFoundationVersion(Integer foundationVersion) {
        this.foundationVersion = foundationVersion;
        return this;
    }

    public Integer getUrlVersion() {
        return this.urlVersion;
    }

    public SharedFacts setUrlVersion(Integer urlVersion) {
        this.urlVersion = urlVersion;
        return this;
    }

    public ShareMethod getMethod() {
        return this.method;
    }

    public SharedFacts setMethod(ShareMethod method) {
        this.method = method;
        return this;
    }

    public String getFactSlug() {
        return this.factSlug;
    }

    public SharedFacts setFactSlug(String factSlug) {
        this.factSlug = factSlug;
        return this;
    }

    public BigDecimal getHighlightStart() {
        return this.highlightStart;
    }

    public SharedFacts setHighlightStart(BigDecimal highlightStart) {
        this.highlightStart = highlightStart;
        return this;
    }

    public BigDecimal getHighlightEnd() {
        return this.highlightEnd;
    }

    public SharedFacts setHighlightEnd(BigDecimal highlightEnd) {
        this.highlightEnd = highlightEnd;
        return this;
    }

    public BigDecimal getViewStart() {
        return this.viewStart;
    }

    public SharedFacts setViewStart(BigDecimal viewStart) {
        this.viewStart = viewStart;
        return this;
    }

    public BigDecimal getViewEnd() {
        return this.viewEnd;
    }

    public SharedFacts setViewEnd(BigDecimal viewEnd) {
        this.viewEnd = viewEnd;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SharedFacts (");

        sb.append(sharedBy);
        sb.append(", ").append(title);
        sb.append(", ").append(foundationVersion);
        sb.append(", ").append(urlVersion);
        sb.append(", ").append(method);
        sb.append(", ").append(factSlug);
        sb.append(", ").append(highlightStart);
        sb.append(", ").append(highlightEnd);
        sb.append(", ").append(viewStart);
        sb.append(", ").append(viewEnd);

        sb.append(")");
        return sb.toString();
    }
}
