/*
 * This file is generated by jOOQ.
*/
package db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Takerevision implements Serializable {

    private static final long serialVersionUID = -234676031;

    private Integer   id;
    private Integer   parentId;
    private Timestamp createdAt;
    private String    createdIp;
    private String    title;
    private String    blocks;

    public Takerevision() {}

    public Takerevision(Takerevision value) {
        this.id = value.id;
        this.parentId = value.parentId;
        this.createdAt = value.createdAt;
        this.createdIp = value.createdIp;
        this.title = value.title;
        this.blocks = value.blocks;
    }

    public Takerevision(
        Integer   id,
        Integer   parentId,
        Timestamp createdAt,
        String    createdIp,
        String    title,
        String    blocks
    ) {
        this.id = id;
        this.parentId = parentId;
        this.createdAt = createdAt;
        this.createdIp = createdIp;
        this.title = title;
        this.blocks = blocks;
    }

    public Integer getId() {
        return this.id;
    }

    public Takerevision setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getParentId() {
        return this.parentId;
    }

    public Takerevision setParentId(Integer parentId) {
        this.parentId = parentId;
        return this;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public Takerevision setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    public String getCreatedIp() {
        return this.createdIp;
    }

    public Takerevision setCreatedIp(String createdIp) {
        this.createdIp = createdIp;
        return this;
    }

    public String getTitle() {
        return this.title;
    }

    public Takerevision setTitle(String title) {
        this.title = title;
        return this;
    }

    public String getBlocks() {
        return this.blocks;
    }

    public Takerevision setBlocks(String blocks) {
        this.blocks = blocks;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Takerevision (");

        sb.append(id);
        sb.append(", ").append(parentId);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(createdIp);
        sb.append(", ").append(title);
        sb.append(", ").append(blocks);

        sb.append(")");
        return sb.toString();
    }
}
