/*
 * This file is generated by jOOQ.
 */
package db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Takerevision implements Serializable {

    private static final long serialVersionUID = -1285534522;

    private Integer       id;
    private Integer       parentId;
    private LocalDateTime createdAt;
    private String        createdIp;
    private String        title;
    private JSONB         blocks;

    public Takerevision() {}

    public Takerevision(Takerevision value) {
        this.id = value.id;
        this.parentId = value.parentId;
        this.createdAt = value.createdAt;
        this.createdIp = value.createdIp;
        this.title = value.title;
        this.blocks = value.blocks;
    }

    public Takerevision(
        Integer       id,
        Integer       parentId,
        LocalDateTime createdAt,
        String        createdIp,
        String        title,
        JSONB         blocks
    ) {
        this.id = id;
        this.parentId = parentId;
        this.createdAt = createdAt;
        this.createdIp = createdIp;
        this.title = title;
        this.blocks = blocks;
    }

    public Integer getId() {
        return this.id;
    }

    public Takerevision setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getParentId() {
        return this.parentId;
    }

    public Takerevision setParentId(Integer parentId) {
        this.parentId = parentId;
        return this;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public Takerevision setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    public String getCreatedIp() {
        return this.createdIp;
    }

    public Takerevision setCreatedIp(String createdIp) {
        this.createdIp = createdIp;
        return this;
    }

    public String getTitle() {
        return this.title;
    }

    public Takerevision setTitle(String title) {
        this.title = title;
        return this;
    }

    public JSONB getBlocks() {
        return this.blocks;
    }

    public Takerevision setBlocks(JSONB blocks) {
        this.blocks = blocks;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Takerevision (");

        sb.append(id);
        sb.append(", ").append(parentId);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(createdIp);
        sb.append(", ").append(title);
        sb.append(", ").append(blocks);

        sb.append(")");
        return sb.toString();
    }
}
